Windows:
 script:  
  - cd 01_XNeuron/XNeuronTest
  - mkdir release
  - cd release
  - qmake ../XNeuronTest.pro  
  - make -j4 check
  - dir
  - tst_xneurontesttest.exe
 tags:
  - windows-*


Linux:
 script:
  - cd 01_XNeuron/XNeuronTest
  - mkdir release
  - cd release
  - qmake ../XNeuronTest.pro  
  - make -j4 check
  - ls
  - ./tst_xneurontesttest
  - cd ../../
  - rm -r ./*
 tags:
  - linux-*