stages:
  - build
  - test

build-test:
  stage: build
  cache:
   paths:
   - 01_XNeuron/XNeuronTest/release
   key: "test1"
  script:
   - cd 01_XNeuron/XNeuronTest
   - mkdir release
   - cd release
   - qmake ../XNeuronTest.pro  
   - make -j4 check


Windows:
 stage: test
 cache:
   paths:
   - 01_XNeuron/XNeuronTest/release
   key: "test1"
 script:
  - cd 01_XNeuron/XNeuronTest/release
  - dir
  - tst_xneurontesttest.exe
 tags:
  - windows-*


Linux:
 stage: test
 cache:
   paths:
   - 01_XNeuron/XNeuronTest/release
   key: "test1"
 script:
  - cd 01_XNeuron/XNeuronTest/release
  - ls
  - ./tst_xneurontesttest
  - cd ../../
  - rm -r ./*
 tags:
  - linux-*